// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Path2Grad.Models;

#nullable disable

namespace Path2Grad.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250505205150_addcvname")]
    partial class addcvname
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Path2Grad.Models.ChatBotConversation", b =>
                {
                    b.Property<int>("ConversationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ConversationID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ConversationId"));

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime");

                    b.Property<int>("StudentId")
                        .HasColumnType("int")
                        .HasColumnName("StudentID");

                    b.HasKey("ConversationId")
                        .HasName("PK__ChatBotC__C050D89705F688F9");

                    b.HasIndex(new[] { "StudentId" }, "IX_ChatBotConversation_StudentID");

                    b.ToTable("ChatBotConversation");
                });

            modelBuilder.Entity("Path2Grad.Models.Cv", b =>
                {
                    b.Property<int>("Cvid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CVID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Cvid"));

                    b.Property<string>("CVName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Cvfile")
                        .HasColumnType("varbinary(max)")
                        .HasColumnName("CVFile");

                    b.Property<string>("Link")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("StudentId")
                        .HasColumnType("int")
                        .HasColumnName("StudentID");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Cvid");

                    b.HasIndex(new[] { "StudentId" }, "IX_CV_StudentID")
                        .IsUnique()
                        .HasFilter("[StudentID] IS NOT NULL");

                    b.ToTable("CV");
                });

            modelBuilder.Entity("Path2Grad.Models.Internship", b =>
                {
                    b.Property<int>("InternshipId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("InternshipID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InternshipId"));

                    b.Property<string>("InternshipLink")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("InternshipName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("StudentId")
                        .HasColumnType("int")
                        .HasColumnName("StudentID");

                    b.HasKey("InternshipId")
                        .HasName("PK__Internsh__01ADE59BBFE1C5AD");

                    b.HasIndex(new[] { "StudentId" }, "IX_Internships_StudentID");

                    b.ToTable("Internships");
                });

            modelBuilder.Entity("Path2Grad.Models.InternshipCertificate", b =>
                {
                    b.Property<int>("InternshipCertificatesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("InternshipCertificatesID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InternshipCertificatesId"));

                    b.Property<byte[]>("Certificate")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<int>("InternshipId")
                        .HasColumnType("int")
                        .HasColumnName("InternshipID");

                    b.HasKey("InternshipCertificatesId")
                        .HasName("PK__Internsh__D378C5AEFB3D51DD");

                    b.HasIndex(new[] { "InternshipId" }, "IX_InternshipCertificates_InternshipID");

                    b.ToTable("InternshipCertificates");
                });

            modelBuilder.Entity("Path2Grad.Models.InternshipWorkFile", b =>
                {
                    b.Property<int>("InternshipWorkFilesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("InternshipWorkFilesID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InternshipWorkFilesId"));

                    b.Property<int>("InternshipId")
                        .HasColumnType("int")
                        .HasColumnName("InternshipID");

                    b.Property<byte[]>("WorkFile")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.HasKey("InternshipWorkFilesId")
                        .HasName("PK__Internsh__A50A41255C06CC0C");

                    b.HasIndex(new[] { "InternshipId" }, "IX_InternshipWorkFiles_InternshipID");

                    b.ToTable("InternshipWorkFiles");
                });

            modelBuilder.Entity("Path2Grad.Models.Message", b =>
                {
                    b.Property<int>("MessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MessageID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MessageId"));

                    b.Property<int>("ConversationId")
                        .HasColumnType("int")
                        .HasColumnName("ConversationID");

                    b.Property<string>("MessageText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("MessageTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Sender")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MessageId")
                        .HasName("PK__Messages__C87C037CF8EF836E");

                    b.HasIndex(new[] { "ConversationId" }, "IX_Messages_ConversationID");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("Path2Grad.Models.Project", b =>
                {
                    b.Property<int>("ProjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ProjectID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProjectId"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumberOfTeam")
                        .HasColumnType("int");

                    b.Property<string>("ProjectName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("ProjectId")
                        .HasName("PK__Projects__761ABED08C04AC41");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("Path2Grad.Models.ProjectField", b =>
                {
                    b.Property<int>("ProjectFieldId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ProjectFieldID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProjectFieldId"));

                    b.Property<string>("ProjectField1")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("ProjectField");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int")
                        .HasColumnName("ProjectID");

                    b.HasKey("ProjectFieldId")
                        .HasName("PK__ProjectF__489DEBAE6509B789");

                    b.HasIndex(new[] { "ProjectId" }, "IX_ProjectField_ProjectID");

                    b.ToTable("ProjectField");
                });

            modelBuilder.Entity("Path2Grad.Models.ProjectFile", b =>
                {
                    b.Property<int>("ProjectFileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProjectFileId"));

                    b.Property<byte[]>("FileContent")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.HasKey("ProjectFileId");

                    b.HasIndex("ProjectId");

                    b.ToTable("ProjectFiles");
                });

            modelBuilder.Entity("Path2Grad.Models.ProjectRequirement", b =>
                {
                    b.Property<int>("RequirementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RequirementId"));

                    b.Property<byte[]>("PdfContent")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<string>("RequirementName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RequirementId");

                    b.HasIndex("ProjectId");

                    b.ToTable("ProjectRequirements");
                });

            modelBuilder.Entity("Path2Grad.Models.ProjectsAdmin", b =>
                {
                    b.Property<int>("AdminId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("AdminID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AdminId"));

                    b.Property<string>("AdminEmail")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("AdminName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("AdminPassword")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<byte[]>("Pic")
                        .HasColumnType("varbinary(max)");

                    b.HasKey("AdminId")
                        .HasName("PK__Projects__719FE4E87D23BB9C");

                    b.HasIndex(new[] { "AdminEmail" }, "UQ__Projects__F2AA7AD96AD4F7D5")
                        .IsUnique();

                    b.ToTable("ProjectsAdmin");
                });

            modelBuilder.Entity("Path2Grad.Models.ProjectsBank", b =>
                {
                    b.Property<int>("ProjectBankId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ProjectBankID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProjectBankId"));

                    b.Property<int>("AdminId")
                        .HasColumnType("int")
                        .HasColumnName("AdminID");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjectName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Requirements")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProjectBankId")
                        .HasName("PK__Projects__2952D07D1CE7D6B7");

                    b.HasIndex(new[] { "AdminId" }, "IX_ProjectsBank_AdminID");

                    b.HasIndex(new[] { "AdminId" }, "UQ_ProjectsBank_AdminID")
                        .IsUnique();

                    b.ToTable("ProjectsBank");
                });

            modelBuilder.Entity("Path2Grad.Models.ProjectsBankProjectField", b =>
                {
                    b.Property<int>("ProjectFieldId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ProjectFieldID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProjectFieldId"));

                    b.Property<int>("ProjectBankId")
                        .HasColumnType("int")
                        .HasColumnName("ProjectBankID");

                    b.Property<string>("ProjectField")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("ProjectFieldId")
                        .HasName("PK__Projects__489DEBAEF90731C3");

                    b.HasIndex(new[] { "ProjectBankId" }, "IX_ProjectsBankProjectField_ProjectBankID");

                    b.ToTable("ProjectsBankProjectField");
                });

            modelBuilder.Entity("Path2Grad.Models.Student", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("StudentID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StudentId"));

                    b.Property<int>("AcademicYear")
                        .HasColumnType("int");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<byte[]>("Pic")
                        .HasColumnType("varbinary(max)");

                    b.Property<int?>("ProjectId")
                        .HasColumnType("int")
                        .HasColumnName("ProjectID");

                    b.Property<string>("StudentEmail")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("StudentName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("StudentPassword")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("StudentId")
                        .HasName("PK__Students__32C52A79DEEA706D");

                    b.HasIndex(new[] { "ProjectId" }, "IX_Students_ProjectID");

                    b.HasIndex(new[] { "StudentEmail" }, "UQ__Students__3569CFDBFD684B18")
                        .IsUnique();

                    b.HasIndex(new[] { "Phone" }, "UQ__Students__5C7E359E925BF2D5")
                        .IsUnique()
                        .HasFilter("([Phone] IS NOT NULL)");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("Path2Grad.Models.Supervisor", b =>
                {
                    b.Property<int>("SupervisorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("SupervisorID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SupervisorId"));

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<byte[]>("Pic")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("ProjectId")
                        .HasColumnType("int");

                    b.Property<string>("Specialization")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("SupervisorEmail")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("SupervisorName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("SupervisorPassword")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("SupervisorId")
                        .HasName("PK__Supervis__6FAABDAF944797EE");

                    b.HasIndex(new[] { "ProjectId" }, "IX_Supervisors_ProjectId");

                    b.HasIndex(new[] { "Phone" }, "UQ__Supervis__5C7E359E33217C14")
                        .IsUnique()
                        .HasFilter("([Phone] IS NOT NULL)");

                    b.HasIndex(new[] { "SupervisorEmail" }, "UQ__Supervis__FAB2DC03A7DD1066")
                        .IsUnique();

                    b.ToTable("Supervisors");
                });

            modelBuilder.Entity("Path2Grad.Models.Task", b =>
                {
                    b.Property<int>("TaskId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("TaskID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TaskId"));

                    b.Property<DateTime>("Deadline")
                        .HasColumnType("datetime");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int")
                        .HasColumnName("ProjectID");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("StudentId")
                        .HasColumnType("int")
                        .HasColumnName("StudentID");

                    b.Property<string>("TaskName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("TaskId")
                        .HasName("PK__Tasks__7C6949D133BB04F3");

                    b.HasIndex(new[] { "ProjectId" }, "IX_Tasks_ProjectID");

                    b.HasIndex(new[] { "StudentId" }, "IX_Tasks_StudentID");

                    b.ToTable("Tasks");
                });

            modelBuilder.Entity("Path2Grad.Models.TeamMember", b =>
                {
                    b.Property<int>("TeamMemberId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("TeamMemberID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TeamMemberId"));

                    b.Property<int>("ProjectId")
                        .HasColumnType("int")
                        .HasColumnName("ProjectID");

                    b.Property<string>("TeamMember1")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("TeamMember");

                    b.HasKey("TeamMemberId")
                        .HasName("PK__TeamMemb__C7C092855F89A1D1");

                    b.HasIndex(new[] { "ProjectId" }, "IX_TeamMember_ProjectID");

                    b.ToTable("TeamMember");
                });

            modelBuilder.Entity("Path2Grad.Models.Track", b =>
                {
                    b.Property<int>("TrackId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("TrackID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TrackId"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Link")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("StudentId")
                        .HasColumnType("int")
                        .HasColumnName("StudentID");

                    b.Property<string>("TrackName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("TrackId");

                    b.HasIndex(new[] { "StudentId" }, "IX_Tracks_StudentID")
                        .IsUnique();

                    b.ToTable("Tracks");
                });

            modelBuilder.Entity("Path2Grad.Models.TrackTest", b =>
                {
                    b.Property<int>("TrackTestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("TrackTestID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TrackTestId"));

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StudentId")
                        .HasColumnType("int")
                        .HasColumnName("StudentID");

                    b.HasKey("TrackTestId");

                    b.HasIndex(new[] { "StudentId" }, "IX_TrackTest_StudentID")
                        .IsUnique();

                    b.ToTable("TrackTest");
                });

            modelBuilder.Entity("SupervisorStudent", b =>
                {
                    b.Property<int>("SupervisorId")
                        .HasColumnType("int")
                        .HasColumnName("SupervisorID");

                    b.Property<int>("StudentId")
                        .HasColumnType("int")
                        .HasColumnName("StudentID");

                    b.HasKey("SupervisorId", "StudentId")
                        .HasName("PK__Supervis__EC86EF08C0CB1384");

                    b.HasIndex(new[] { "StudentId" }, "IX_SupervisorStudent_StudentID");

                    b.ToTable("SupervisorStudent", (string)null);
                });

            modelBuilder.Entity("Path2Grad.Models.ChatBotConversation", b =>
                {
                    b.HasOne("Path2Grad.Models.Student", "Student")
                        .WithMany("ChatBotConversations")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__ChatBotCo__Stude__60A75C0F");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Path2Grad.Models.Cv", b =>
                {
                    b.HasOne("Path2Grad.Models.Student", "Student")
                        .WithOne("Cv")
                        .HasForeignKey("Path2Grad.Models.Cv", "StudentId");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Path2Grad.Models.Internship", b =>
                {
                    b.HasOne("Path2Grad.Models.Student", "Student")
                        .WithMany("Internships")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Internshi__Stude__4F7CD00D");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Path2Grad.Models.InternshipCertificate", b =>
                {
                    b.HasOne("Path2Grad.Models.Internship", "Internship")
                        .WithMany("InternshipCertificates")
                        .HasForeignKey("InternshipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Internshi__Inter__5535A963");

                    b.Navigation("Internship");
                });

            modelBuilder.Entity("Path2Grad.Models.InternshipWorkFile", b =>
                {
                    b.HasOne("Path2Grad.Models.Internship", "Internship")
                        .WithMany("InternshipWorkFiles")
                        .HasForeignKey("InternshipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Internshi__Inter__52593CB8");

                    b.Navigation("Internship");
                });

            modelBuilder.Entity("Path2Grad.Models.Message", b =>
                {
                    b.HasOne("Path2Grad.Models.ChatBotConversation", "Conversation")
                        .WithMany("Messages")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Messages__Conver__6477ECF3");

                    b.Navigation("Conversation");
                });

            modelBuilder.Entity("Path2Grad.Models.ProjectField", b =>
                {
                    b.HasOne("Path2Grad.Models.Project", "Project")
                        .WithMany("ProjectFields")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__ProjectFi__Proje__74AE54BC");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Path2Grad.Models.ProjectFile", b =>
                {
                    b.HasOne("Path2Grad.Models.Project", "Project")
                        .WithMany("projectFiles")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Path2Grad.Models.ProjectRequirement", b =>
                {
                    b.HasOne("Path2Grad.Models.Project", "Project")
                        .WithMany("Requirements")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Path2Grad.Models.ProjectsBank", b =>
                {
                    b.HasOne("Path2Grad.Models.ProjectsAdmin", "Admin")
                        .WithOne("ProjectsBank")
                        .HasForeignKey("Path2Grad.Models.ProjectsBank", "AdminId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__ProjectsB__Admin__7B5B524B");

                    b.Navigation("Admin");
                });

            modelBuilder.Entity("Path2Grad.Models.ProjectsBankProjectField", b =>
                {
                    b.HasOne("Path2Grad.Models.ProjectsBank", "ProjectBank")
                        .WithMany("ProjectsBankProjectFields")
                        .HasForeignKey("ProjectBankId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__ProjectsB__Proje__7E37BEF6");

                    b.Navigation("ProjectBank");
                });

            modelBuilder.Entity("Path2Grad.Models.Student", b =>
                {
                    b.HasOne("Path2Grad.Models.Project", "Project")
                        .WithMany("Students")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK__Students__Projec__48CFD27E");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Path2Grad.Models.Supervisor", b =>
                {
                    b.HasOne("Path2Grad.Models.Project", "Project")
                        .WithMany("Supervisors")
                        .HasForeignKey("ProjectId");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Path2Grad.Models.Task", b =>
                {
                    b.HasOne("Path2Grad.Models.Project", "Project")
                        .WithMany("Tasks")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Tasks__ProjectID__6E01572D");

                    b.HasOne("Path2Grad.Models.Student", "Student")
                        .WithMany("Tasks")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Tasks__StudentID__6EF57B66");

                    b.Navigation("Project");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Path2Grad.Models.TeamMember", b =>
                {
                    b.HasOne("Path2Grad.Models.Project", "Project")
                        .WithMany("TeamMembers")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__TeamMembe__Proje__71D1E811");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Path2Grad.Models.Track", b =>
                {
                    b.HasOne("Path2Grad.Models.Student", "Student")
                        .WithOne("Track")
                        .HasForeignKey("Path2Grad.Models.Track", "StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Path2Grad.Models.TrackTest", b =>
                {
                    b.HasOne("Path2Grad.Models.Student", "Student")
                        .WithOne("TrackTest")
                        .HasForeignKey("Path2Grad.Models.TrackTest", "StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("SupervisorStudent", b =>
                {
                    b.HasOne("Path2Grad.Models.Student", null)
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Superviso__Stude__6B24EA82");

                    b.HasOne("Path2Grad.Models.Supervisor", null)
                        .WithMany()
                        .HasForeignKey("SupervisorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Superviso__Super__6A30C649");
                });

            modelBuilder.Entity("Path2Grad.Models.ChatBotConversation", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("Path2Grad.Models.Internship", b =>
                {
                    b.Navigation("InternshipCertificates");

                    b.Navigation("InternshipWorkFiles");
                });

            modelBuilder.Entity("Path2Grad.Models.Project", b =>
                {
                    b.Navigation("ProjectFields");

                    b.Navigation("Requirements");

                    b.Navigation("Students");

                    b.Navigation("Supervisors");

                    b.Navigation("Tasks");

                    b.Navigation("TeamMembers");

                    b.Navigation("projectFiles");
                });

            modelBuilder.Entity("Path2Grad.Models.ProjectsAdmin", b =>
                {
                    b.Navigation("ProjectsBank");
                });

            modelBuilder.Entity("Path2Grad.Models.ProjectsBank", b =>
                {
                    b.Navigation("ProjectsBankProjectFields");
                });

            modelBuilder.Entity("Path2Grad.Models.Student", b =>
                {
                    b.Navigation("ChatBotConversations");

                    b.Navigation("Cv");

                    b.Navigation("Internships");

                    b.Navigation("Tasks");

                    b.Navigation("Track");

                    b.Navigation("TrackTest");
                });
#pragma warning restore 612, 618
        }
    }
}
